# Introduction

This provides an overview of the PhD program in Epidemiology at McGill.

Epidemiology is the study and analysis of the patterns and causes of disease in human populations. It forms the core discipline of public health by identifying the distribution and determinants of health and disease, and by gaining the etiologic understanding to intervene toward the improvement of population health. The PhD program in epidemiology at McGill trains scientists and health professionals to design and conduct studies, analyze health data and effectively communicate scientific results, and to gain novel insights into the causes and prevention of diseases at the population level. Epidemiologic work at the doctoral level involves a thorough integration of biological knowledge of pathogenesis, statistical knowledge of quantitative analysis and causal inference, and sociological knowledge to place these insights in the context of dynamic and interconnected human populations. Major areas of strength at McGill include epidemiologic methods, clinical epidemiology, infectious diseases, social epidemiology, pharmacoepidemiology, public and population health, global health, environmental epidemiology, chronic diseases and aging, and perinatal epidemiology.

## Competencies
Our program aims to prepare our students for successful careers in epidemiology. Upon successful completion of the PhD in Epidemiology at McGill, we aim for our students to: 

- Understand the difference between descriptive and etiologic epidemiologic studies, and the value of both designs for public health science;
- Develop a thorough understanding of modern epidemiologic methods and how they are utilized in the service of descriptive, predictive, and etiologic study designs;
- Apply quantitative skills to the analysis of epidemiologic data using statistical software;
- Systematically and critically review the epidemiologic literature, synthesize existing evidence, and identify important gaps in knowledge;
- Design, write, and critique an independent research proposal for answering epidemiologic questions;

## High-Level Program Overview
Successful completion of the PhD program in EBOH involves 4 key milestones:
- Required coursework;
- Passing a comprehensive exam;
- Developing and defending a thesis protocol; and
- Writing and defending the doctoral thesis.

The timeline for program completion varies depending on each student's circumstances and subject matter, but most of our students complete the PhD in around 5 years. 

- 