# Milestones

- 25 course credits (16 required + 9 elective)
- Comprehensive Exam
- Protocol Defense
- Thesis Defense

Options (additional 6 credits + conditions):

- Global Health
- Population Dynamics
- Pharmacoepidemiology

Funding

- CIHR (early October)
- FRQS (mid October)
- SSHRC (early November)
- McGill internal studentships (April 15)
- TAships (required, once)
- RAships (12 hrs/week?)
- Should mention how “guaranteed funding” works here.

Tracking Forms

- Supervisor nomination form (May 15)
- Annual submission (May 15)

Required coursework:
Year 0 (prep):

- 601 Intro Epi
- 602 Foundations of Pop Health
- 605 Critical appraisal of Epi studies
- 607 Biostats I
- 613 Software
- 603 Intermediate Epi
- 621 Biostats II

Year 1 

- Fall:
    - 703 Study Design (Basso Kramer/Tamblyn)
    - 704 Methods I (Kaufman)
- Winter:
    - 705 Methods II (Chevrier / Infante-Rivard)
    - 706 Seminar (Harper)
- Summer:
    - 701 Comprehensive Exam (June)

Year 2

- Fall:
    - 702 PhD proposal (Nandi / Abrahamowicz)
    - 707 Research Design (Basta / Wolfson)
- Winter:
    - 702 PhD proposal (Nandi / Abrahamowicz)

Elective coursework (9 credits):

- 500-level or higher
- 3 credits in biostatistics (minimum)
    - Bayesian
    - Correlated
    - Causal
    - Survival
    - Others to come (e.g., GIS, prediction modelling, ID modelling)
- 6 credits in epidemiology and/or substantive topic (normally related to the thesis topic). Courses must be chosen in consultation with the student’s supervisor and/or the degree program’s director or adviser.
    - Evidence synthesis
    - Social
    - Clinical
    - Cancer…
    - Psychiatric
    - Pharmaco
    - Impact Evaluation

Ethics Requirement

- Tri-Council Policy for Ethical Conduct of Research (TCPS-2)

PhD Thesis Protocol

- Ideally in Winter of Year 2
- 10 page written proposal
- Oral defense with instructors and 1 added committee member

Thesis

- Original work (manuscripts or “book”)
- Committee requirements

PhD Defense:

- External evaluation
- Oral defense
- See GPS for “official” guidelines
