# Policies

## Progress Tracking

## Research Ethics 

## Fast-Track from MSc to PhD

The transfer policy applies ONLY to students in Epidemiology and Biostatistics programs.
A student who has been accepted into the M.Sc. program can request transfer into the Ph.D. program. The formal transfer into the Ph.D. program should occur within 12 months of initial enrollment in the Master's program.

In order to transfer from the M.Sc. to the Ph.D. program, the M.Sc. student must complete all required courses for the M.Sc. program with a minimum GPA of 3.7.

REQUIRED DOCUMENTS
Biostatistics
A three-page outline of the proposed Ph.D. thesis proposal;
Letters of support from the current M.Sc. supervisor(s) and proposed Ph.D. supervisor(s). In cases where this is the same person, one additional letter from a faculty member in the Department is required. The letter from the proposed Ph.D. supervisor(s) must include a statement of financial support for the candidate and research.
Epidemiology

A three to five-page outline of the proposed Ph.D. thesis proposal including:
Research question
Background and brief literature review indicating the importance of the proposed research
Preliminary research design
Data source
Preliminary analysis plan
A timeline for completion of the Ph.D. program
Letters of support from the current M.Sc. supervisor(s) and proposed Ph.D. supervisor(s). In cases where this is the same person, one additional letter from a faculty member in the Department is required. The letter from the proposed Ph.D. supervisor(s) must include a statement of financial support for the candidate and research.
The transfer application material must be submitted by April 25 to gradadmin.eboh@mcgill.ca.

## Directed Reading Courses

**Directed Reading courses complement offerings in the department or elsewhere at McGill or other universities. They are NOT substitutes for existing courses but are, rather, ways for students in the programs to enrich their education in an organized way on topics not otherwise covered or not covered sufficiently (in depth or breadth) in existing courses.** 

Students enrolled in the department may take Directed Reading courses for credit towards a degree under the rubric of the Special Topics offerings. These courses may be for 1, 2, or 3 credits. Directed Reading courses should conform to the usual semester format unless the specific circumstances of the course require flexibility. However, students are expected to complete such a course within no more than any six month period.

While there is much flexibility in what constitutes such a course, certain requirements must be met before work can begin.

1. Students must themselves propose a supervising faculty member with whom to work.

2. With the faculty supervisor, students must prepare an adequate project proposal commensurate with the number of credits sought that includes:

a. The rationale for doing this work as a Directed Reading course and for the number of credits sought. As well, this statement should indicate how it relates to, but is separate from, thesis work when the student is in a thesis program.

b. An outline of the work to be done and the final product/output to be submitted. If a Reading Course is being proposed, a preliminary bibliography and a planned reading schedule should be included.

c. A timetable, with appropriate milestones to assess a student’s progress and the measures to be used to evaluate the work (e.g., number of written assignments and their length). A student’s faculty supervisor will be responsible for this evaluation as is the case for “regular” courses.

d. A timetable indicating when the student and faculty supervisor will meet.

Students will be expected to submit for approval in advance material that provides the objectives and methods to be used for the IS/DR work.

3. The project proposal, signed by both the student and the supervisor, should be submitted to the Student Affairs Office a minimum of one month prior to the start of the semester in which the course will take place. The director, along with one other person on the Program Committee who has accepted responsibility for curriculum matters, will review the proposal and determine if it is to be approved. Once approved internally, a copy will be sent to the Director of Graduate Studies as well as to the Department’s Graduate Studies Office, with a request that the latter obtain a Special Topics course number for the offering. A copy of the final approved version of the course content will be placed in the student’s file.

## Policy on Departmental Seminars

Updated November 9th, 2015
The Department considers attendance at its seminars an important component of training and expects all students to attend as frequently as possible.

All Epidemiology and Public Health graduate students will be expected to attend 60% of the Epidemiology Seminars each term irrespective of their program year. Attendance at seminars will be mandatory to maintain “good standing” during academic studies. This means that attendance at seminars will be required to maintain eligibility for Departmental support for prizes, financial aid, travel awards, studentship applications, etc. Attendance at Biostatistics or at other seminars on campus or in teaching hospitals will be encouraged as always depending on one's areas of interest but will not be mandatory.

Students who will be unable to attend 60% of the seminars should send a request for an exemption to the chairs office justifying their absence (eg. residing outside of Montreal, travel relating to their studies, family reasons).

## Policy on Email

University Policy Concerning E-Mail As An Official Means Of Communication With Students. E-mail is an official means of communication between McGill University and its students.
 

In order to satisfy the need for timely and efficient communication, and to provide a better service to its students, McGill University has instituted a policy that establishes e-mail as an official means of communicating with students.

Upon registration at McGill, each student is assigned an official McGill e-mail address and a McGill e-mail box. This address may be viewed and verified via Minerva, under the Personal menu.

The McGill E-mail Address points to the McGill e-mail box by default for all students. As with all official University communications, it is the student's responsibility to ensure that time-critical e-mail is accessed, read, and acted upon in a timely fashion. If a student chooses to forward University e-mail to another e-mail mailbox, it is that student's responsibility to ensure that the alternate account is viable.

This policy applies to all McGill students and employees who manage official communications with students.

For confidential and official communication requiring an original signature, communication is by (physical) mail. Therefore, please ensure that your current postal address is updated on Minerva.  Students must also inform the Student Affairs Office and complete the details in Minerva.

**Please keep in mind that although we do our best to keep all the information on the website up to date, we may have missed something. If you ever have questions about anything please contact the Student Affairs Office to clarify. 
